# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy Telegram Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Zip file
      run: |
        zip -r rust-money-tracker-bot.zip * -x ./.gihtub -x ./.git -x ./.gitignore -x ./target -x ./LICENSE -x ./users_data.json

    - name: Copy Files to Remote Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "rust-money-tracker-bot.zip"
        target: /home/rust-expenses-bot/

    - name: SSH into Server and Build App
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          sudo systemctl stop rust-expenses-bot.service
          cd /home/rust-expenses-bot/
          rm -r ./project
          mkdir ./project
          rm -r ./build
          mkdir ./build
          unzip rust-money-tracker-bot.zip -d ./project
          cargo build --release
          cd target
          cd release
          mv ./ ../../../build/
          sudo systemctl start rust-expenses-bot.service